version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: deploy/restart_server.sh
      timeout: 30
      runas: root
